apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vault-secret.fullname" . }}
  labels:
    {{- include "vault-secret.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only : "true"
            vault.hashicorp.com/agent-inject-secret-secret.yaml: aws/creds/{{ include "vault-secret.fullname" . }}-bucket-0
            vault.hashicorp.com/agent-inject-template-secret.yaml: |
             {{ "{{-" }} with secret "aws/creds/{{ include "vault-secret.fullname" . }}-bucket-0" {{ "-}}" }}
             apiVersion: v1
             stringData:
               ACCESS_KEY_ID:  {{ "{{" }} .Data.access_key {{ "}}" }},
               ACCESS_SECRET_KEY: {{ "{{" }} .Data.secret_key {{ "}}" }},
               ACCESS_SESSION_TOKEN: {{ "{{" }} .Data.security_token {{ "}}" }}
             kind: Secret
             metadata:
               name: {{ include "vault-secret.fullname" . }}-aws-secret
               namespace: {{ .Release.Namespace }}
             {{ "{{" }} end {{ "}}" }}
            vault.hashicorp.com/role: {{ include "vault-secret.fullname" . }}-bucket-0
            vault.hashicorp.com/secret-volume-path: /kubesecret
            vault.hashicorp.com/service: {{ .Values.vault.s3Addr }}
            vault.hashicorp.com/tls-skip-verify: {{ .Values.vault.skipTLSVerify | quote }}
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          labels:
            {{- include "vault-secret.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "vault-secret.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: 
                {{- toYaml .Values.command | nindent 16 }}
              args:
                {{- toYaml .Values.args | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 5
---
