apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres 
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: test
  project: default
  source:
    path: postgres
    targetRevision: dev
    helm:
      releaseName: adv-pgsql
    repoURL: git@github.com:advatys/postgres.git 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
