{{- if .Values.cluster.backup.enabled }}
apiVersion: s3.advatys.com/v1alpha1
kind: Bucket
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: {{ include "vault-secret.fullname" . }}
  labels:
    {{- include "vault-secret.labels" . | nindent 4 }}
spec:
  permissions:
  - actions:
        - "*"
    resources:
        - "/*"
        - ""
    subjects:
       - type: KubernetesServiceAccountt
         cluster: {{ .Values.kubeClusterName }}
         name: {{ include "vault-secret.serviceAccountName" . }} 
         namespace: {{ .Release.Namespace }} 
    effect: Allow
{{- end }}
