{{- if .Values.cluster.backup.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "vault-secret.serviceAccountName" . }}
  labels:
    {{- include "vault-secret.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    argocd.argoproj.io/sync-wave: "-5"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault-secret.serviceAccountName" . }}
  labels:
    {{- include "vault-secret.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    argocd.argoproj.io/sync-wave: "-5"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-secret.serviceAccountName" . }}
  labels:
    {{- include "vault-secret.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-secret.serviceAccountName" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "vault-secret.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- end }}
